
colorscheme: classic

highlight: rainbow

page_width: 48

rss: false 

mathjax:
  enabled: true 

nav:
  home: /
  articles: /notes/
  search: /search/

social_links:
  - icon: twitter
    link: https://x.com/TaipeiTsunami
  - icon: facebook
    link: https://www.facebook.com/profile.php?id=100000736195394
  - icon: github
    link: https://github.com/tinytsunami

archive:
  sort_updated: false

post:
  show_updated: true

copyright:
  start_year: 2016

error_404:
  enabled: true
  title: "404 Page Not Found"
  description: "The page you are looking for might have been removed, had its name changed, or is temporarily unavailable."

logo:
  enabled: true
  width: 72
  height: 72
  url: /images/logo.png
  gravatar: false
  grayout: true

favicon:
  desktop:
    url: /images/icon.png
    gravatar: false
  android:
    url: /images/icon.png
    gravatar: false
  apple:
    url: /images/icon.png
    gravatar: false
