# ---------------------------------------------------------------
# Theme Core Configuration Settings
# ---------------------------------------------------------------

cache:
  enable: true

custom_file_path:
  style: source/_data/styles.styl

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

scheme: Gemini

darkmode: true

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

favicon:
  small: /images/icon.png
  medium: /images/icon.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg

custom_logo: /images/icon.png

# Creative Commons 4.0 International License.
creative_commons:
  license: cc-zero

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  game: https://tinytsunami.itch.io/ || fas fa-gamepad
  # commonweal: /404/ || fa fa-heartbeat

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

sidebar:
  position: right

avatar:
  url: /images/head.jpg
  rounded: true

social:
  GitHub: https://github.com/tinytsunami || fab fa-github
  Twitter: https://twitter.com/TaipeiTsunami || fab fa-twitter
  FB Page: https://www.facebook.com/profile.php?id=100000736195394 || fab fa-facebook
  YouTube: https://www.youtube.com/channel/UCtqp9w_uA_LohDm0YXNWqSA || fab fa-youtube

links_settings:
  icon: fa fa-link
  layout: block

links:
  Cyris's Blog: https://blog.cyris.tw
  Robert's Blog: https://poyu-liao.github.io/blog

# ---------------------------------------------------------------
# Footer Settings
# ---------------------------------------------------------------

language_switcher: true

footer:
  since: 2018
  icon:
    name: fa fa-bomb
    animated: true
    color: "#495057"

# ---------------------------------------------------------------
# Tags Settings
# ---------------------------------------------------------------
note:
  style: flat
  icons: true

# ---------------------------------------------------------------
# Math Formulas Render Support
# ---------------------------------------------------------------

math:
  every_page: true
  mathjax:
    enable: true

# ---------------------------------------------------------------
# External Libraries
# ---------------------------------------------------------------

fancybox: true

# ---------------------------------------------------------------
# Animation Settings
# ---------------------------------------------------------------

motion:
  enable: false

# ---------------------------------------------------------------
# Comments Settings
# ---------------------------------------------------------------


# ---------------------------------------------------------------
# Search Services
# ---------------------------------------------------------------

local_search:
  enable: true